[package]
name = "gradient-tool"
version = "0.0.1"
authors = ["Zachary Catlin <z@zc.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
